### ISSUE TITLE
app won't start, only logo breathing splash screen

### ISSUE THREAD

**Issue by awesome14** [deadlyjack/Acode#277]
I installed off f-droid. App remains on splash screen. Tried double tap, tap. How do I get past splash screen. Thanks for the help.

**Comment by ashjas** [comment]
+1
Came here to report same issue with fdroid version on a non google play services phone.
```
10-16 12:11:33.591  1468  2063 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.foxdebug.acode/.MainActivity bnds=[32,460][235,803]} from uid 1000
10-16 12:11:33.608  1468  1538 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10298; state: DISABLED
10-16 12:11:33.608  1468  1538 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10298; state: ENABLED
10-16 12:11:33.608  1468  1545 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10298; state: ENABLED
10-16 12:11:33.625  2735  2735 W Choreographer: Frame time is 0.130398 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
10-16 12:11:33.632  1468  1545 I ActivityManager: Start proc 13230:com.foxdebug.acode/u0a298 for pre-top-activity {com.foxdebug.acode/com.foxdebug.acode.MainActivity}
10-16 12:11:33.633 13230 13230 E .foxdebug.acod: Not starting debugger since process cannot load the jdwp agent.
10-16 12:11:33.637 13230 13230 W .foxdebug.acod: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
10-16 12:11:33.651  1468  1539 W WindowManager: Unable to find process with pid=2735 uid=1000
10-16 12:11:33.661 13230 13230 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
10-16 12:11:33.662 13230 13230 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
10-16 12:11:33.676   920  2789 W DisplayIdentification: Invalid EDID: falling back to serial number due to missing display name.
10-16 12:11:33.676   920  2789 W DisplayIdentification: Invalid EDID: falling back to ASCII text due to missing serial number.
10-16 12:11:33.681 13230 13230 I CordovaLog: Changing log level to DEBUG(3)
10-16 12:11:33.681 13230 13230 I CordovaActivity: Apache Cordova native platform version 9.1.0 is starting
10-16 12:11:33.681 13230 13230 D CordovaActivity: CordovaActivity.onCreate()
10-16 12:11:33.686 13230 13230 I WebViewFactory: Loading com.android.webview version 93.0.4577.82 (code 457708203)
10-16 12:11:33.690 13230 13230 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/webview/lib/arm64:/product/app/webview/webview.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
10-16 12:11:33.703 13230 13230 I cr_WVCFactoryProvider: Loaded version=93.0.4577.82 minSdkVersion=21 isBundle=false multiprocess=true packageId=2
10-16 12:11:33.714 13230 13230 I cr_LibraryLoader: Successfully loaded native library
10-16 12:11:33.715 13230 13230 I cr_CachingUmaRecorder: Flushed 7 samples from 7 histograms.
10-16 12:11:33.722  1468 12803 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10298; state: DISABLED
10-16 12:11:33.722  1468  1545 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10298; state: ENABLED
10-16 12:11:33.749  2303  2303 D Zygote  : Forked child process 17053
10-16 12:11:33.751  1468  1545 I ActivityManager: Start proc 17053:com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i10 for  {com.foxdebug.acode/org.chromium.content.app.SandboxedProcessService0:0}
10-16 12:11:33.752 13230 17044 W chromium: [WARNING:dns_config_service_android.cc(153)] Failed to read DnsConfig.
10-16 12:11:33.767 17053 17053 E ocessService0:: Not starting debugger since process cannot load the jdwp agent.
10-16 12:11:33.785  1468  5809 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10298; state: ENABLED
10-16 12:11:33.800 13230 13230 D SystemWebViewEngine: CordovaWebView is running on device made by: Xiaomi
10-16 12:11:33.802 13230 13230 D PluginManager: init()
10-16 12:11:33.802 13230 13230 D PluginManager: startupPlugins: put - Clipboard
10-16 12:11:33.802 13230 13230 D PluginManager: startupPlugins: put - Permissions
10-16 12:11:33.802 13230 13230 D PluginManager: startupPlugins: put - BuildInfo
10-16 12:11:33.802 13230 13230 D PluginManager: startupPlugins: put - Device
10-16 12:11:33.810   828   828 W SDM     : HWCDisplay::GetHWCLayer: [0] GetLayer(1510) failed: no such layer
10-16 12:11:33.811   920   920 W HwcComposer: command 0x3000000 generated error 3
10-16 12:11:33.814 17053 17053 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-16 12:11:33.814 17053 17053 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-16 12:11:33.815 17053 17053 I cr_WebViewApkApp: Launched version=93.0.4577.82 minSdkVersion=21 isBundle=false processName=com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0
10-16 12:11:33.816 13230 13230 D FileUtils: Unrecognized extra filesystem identifier: assets
10-16 12:11:33.816 13230 13230 D PluginManager: getPlugin - put: File
10-16 12:11:33.816 13230 13230 D PluginManager: startupPlugins: put - Ftp
10-16 12:11:33.816 13230 13230 D PluginManager: startupPlugins: put - InAppBrowser
10-16 12:11:33.816 13230 13230 D PluginManager: startupPlugins: put - IntentPlugin
10-16 12:11:33.817 13230 13230 D PluginManager: getPlugin - put: NavigationBar
10-16 12:11:33.817 13230 13230 D PluginManager: startupPlugins: put - SDcard
10-16 12:11:33.817 13230 13230 D PluginManager: startupPlugins: put - Sftp
10-16 12:11:33.817 17053 17053 I cr_ChildProcessService: Creating new ChildProcessService pid=17053
10-16 12:11:33.822 13230 13230 D PluginManager: getPlugin - put: StatusBar
10-16 12:11:33.822 13230 13230 D PluginManager: startupPlugins: put - System
10-16 12:11:33.824 13230 13230 W WhitelistPlugin: Found <access launch-external> within config.xml. Please use <allow-intent> instead.
10-16 12:11:33.824 13230 13230 D Whitelist: Unlimited access to network resources
10-16 12:11:33.825 13230 13230 D PluginManager: getPlugin - put: Whitelist
10-16 12:11:33.825 13230 13230 D PluginManager: startupPlugins: put - Webserver
10-16 12:11:33.825 13230 13230 D PluginManager: startupPlugins: put - CoreAndroid
10-16 12:11:33.825 13230 13230 D CordovaWebViewImpl: >>> loadUrl(file:///android_asset/www/index.html)
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: QUALCOMM build                   : 42297a4, I9e9b240040
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Build Date                       : 03/19/21
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.07
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Local Branch                     : 
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.9.1.R1.11.00.00.604.070
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Remote Branch                    : NONE
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Build Config                     : S P 10.0.6 AArch64
10-16 12:11:33.831 13230 17079 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-16 12:11:33.833 13230 17049 W cr_media: Requires BLUETOOTH permission
10-16 12:11:33.836 13230 17079 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
10-16 12:11:33.837 13230 13230 W Chrome_InProcGp: type=1400 audit(0.0:8228): avc: denied { search } for name="2c00000.qcom,kgsl-3d0" dev="sysfs" ino=41299 scontext=u:r:untrusted_app:s0:c42,c257,c512,c768 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=dir permissive=0 app=com.foxdebug.acode
10-16 12:11:33.839 13230 17079 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
10-16 12:11:33.839 13230 17079 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
10-16 12:11:33.840 13230 13230 D CordovaActivity: Started the activity.
10-16 12:11:33.841 17053 17077 I cr_LibraryLoader: Successfully loaded native library
10-16 12:11:33.841 13230 13230 D CordovaActivity: Resumed the activity.
10-16 12:11:33.843 17053 17077 I cr_CachingUmaRecorder: Flushed 1 samples from 1 histograms.
10-16 12:11:33.858 17053 17077 W SystemServiceRegistry: No service published for: uimode
10-16 12:11:33.925 13230 13230 D CordovaWebViewImpl: onPageDidNavigate(file:///android_asset/www/index.html)
10-16 12:11:33.926 13230 13230 D PluginManager: postMessage: onPageStarted
10-16 12:11:33.934  1468  1543 I ActivityTaskManager: Displayed com.foxdebug.acode/.MainActivity: +331ms
10-16 12:11:33.952 13230 13230 D JsMessageQueue: Set native->JS mode to EvalBridgeMode
10-16 12:11:34.043 13230 17093 D PluginManager: getPlugin - put: CoreAndroid
10-16 12:11:34.045 13230 13230 D PluginManager: postMessage: spinner
10-16 12:11:34.046 13230 17093 D PluginManager: getPlugin - put: BuildInfo
10-16 12:11:34.047 13230 17093 W System.err: java.lang.NoSuchFieldException: FLAVOR
10-16 12:11:34.048 13230 17093 W System.err:    at java.lang.Class.getField(Class.java:1604)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.buildinfo.BuildInfo.getClassField(BuildInfo.java:277)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.buildinfo.BuildInfo.getClassFieldString(BuildInfo.java:210)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.buildinfo.BuildInfo.init(BuildInfo.java:155)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.buildinfo.BuildInfo.execute(BuildInfo.java:77)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.PluginManager.exec(PluginManager.java:139)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
10-16 12:11:34.048 13230 17093 W System.err:    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
10-16 12:11:34.048 13230 17093 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
10-16 12:11:34.048 13230 17093 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:335)
10-16 12:11:34.048 13230 17093 W System.err:    at android.os.Looper.loop(Looper.java:183)
10-16 12:11:34.048 13230 17093 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
10-16 12:11:34.050 13230 17093 D PluginManager: getPlugin - put: Device
10-16 12:11:34.106  1468 12803 W WindowManager: Unable to find process with pid=2735 uid=1000
10-16 12:11:34.110   920   920 E Layer   : [Surface(name=Task=1)/@0xf66fe8c - animation-leash#0] No local sync point found
10-16 12:11:34.110   920   920 E Layer   : [Surface(name=Task=4107)/@0xfc03f97 - animation-leash#0] No local sync point found
10-16 12:11:34.118   920   920 E Layer   : [Surface(name=Task=1)/@0xf66fe8c - animation-leash#0] No local sync point found
10-16 12:11:34.118   920   920 E Layer   : [Surface(name=Task=4107)/@0xfc03f97 - animation-leash#0] No local sync point found
10-16 12:11:34.188 13230 13230 D CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
10-16 12:11:34.188 13230 13230 D PluginManager: postMessage: onPageFinished
10-16 12:11:38.770   637   642 E android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup43: Permission denied
10-16 12:11:38.767   637   637 W Binder:637_1: type=1400 audit(0.0:8229): avc: denied { read } for name="wakeup43" dev="sysfs" ino=78987 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
10-16 12:11:38.772   603   603 I hwservicemanager: getTransport: Cannot find entry android.hardware.power.stats@1.0::IPowerStats/default in either framework or device manifest.
10-16 12:11:38.774   603   603 I hwservicemanager: getTransport: Cannot find entry android.hardware.power@1.0::IPower/default in either framework or device manifest.

```

**Comment by deadlyjack** [comment]
Please provide the app version, device information.
