### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by JQTechnologies** [deadlyjack/Acode#295]
yarn build-run output:

```yarn run v1.22.15
$ yarn config-build d && webpack && cordova run android
$ node ./utils/config.js d
/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'mini-css-extract-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/media/jq/Backupy/Stworzone/Acode/webpack.config.js:2:30)
    at Module._compile (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/usr/share/nodejs/yargs/yargs.js:620:18)
    at /usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/nodejs/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by deadlyjack** [comment]
Run `npm install` to install packages, before building.
