### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by NiceSapien** [deadlyjack/Acode#390]
I have cloned Acode on my local machine. I tried to build it with the command `yarn build android paid d`, but it didnt work. I did npm install, Corodova is Installed too. Here's the error:
```cmd
yarn run v1.22.18
$ sh utils/scripts/build.sh android paid d
node ./utils/config.js d paid
|--- Reinstalling platform ANDROID ---|
DONE! Removing admob-plus-cordova
(node:22012) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) i
nstead
(Use `node --trace-deprecation ...` to show where the warning was created)

webpack --progress --mode development
[webpack-cli] Error: ENOENT: no such file or directory, stat 'C:\Users\class\code\Acode\www\css\build'
    at Object.statSync (node:fs:1538:3)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at clearOutputDir (C:\Users\class\code\Acode\webpack.config.js:81:6)
    at module.exports (C:\Users\class\code\Acode\webpack.config.js:44:3)
    at loadConfigByPath (C:\Users\class\code\Acode\node_modules\webpack-cli\lib\webpack-cli.js:1747:27)
    at async WebpackCLI.loadConfig (C:\Users\class\code\Acode\node_modules\webpack-cli\lib\webpack-cli.js:1832:30)
    at async WebpackCLI.createCompiler (C:\Users\class\code\Acode\node_modules\webpack-cli\lib\webpack-cli.js:2187:18)
    at async WebpackCLI.runWebpack (C:\Users\class\code\Acode\node_modules\webpack-cli\lib\webpack-cli.js:2323:16)
    at async Command.<anonymous> (C:\Users\class\code\Acode\node_modules\webpack-cli\lib\webpack-cli.js:1060:13) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\class\\code\\Acode\\www\\css\\build'
}
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\class\code\Acode\www\css\build'
    at Object.readdirSync (node:fs:1392:3)
    at Object.<anonymous> (C:\Users\class\code\Acode\utils\loadStyles.js:8:21)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\class\\code\\Acode\\www\\css\\build'
}
cordova build android

===================================================
==== Changed provider to com.foxdebug.provider ====
===================================================

[Gradle Properties] Detected Gradle property "android.useAndroidX" with the value of "true", Cordova's recommended value is "false"
[Gradle Properties] Detected Gradle property "android.enableJetifier" with the value of "true", Cordova's recommended value is "false"

=========================================================
==== Changed provider to com.foxdebug.acode.provider ====
=========================================================

Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Requirements check failed for JDK 1.8.x! Detected version: 17.0.2
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NiceSapien** [comment]
everything worked, but now its showing this:
```bash
cordova build android

===================================================
==== Changed provider to com.foxdebug.provider ====
===================================================

[Gradle Properties] Detected Gradle property "android.useAndroidX" with the value of "true", Cordova's recommended value is "false"
[Gradle Properties] Detected Gradle property "android.enableJetifier" with the value of "true", Cordova's recommended value is "false"

=========================================================
==== Changed provider to com.foxdebug.acode.provider ====
=========================================================

Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Requirements check failed for JDK 1.8.x! Detected version: 17.0.2
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by deadlyjack** [comment]
okay, that's great

**Comment by nicesapien-too** [comment]
Bro, there still is an error. Can you help me fix that? @deadlyjack
