### ISSUE TITLE
Build failed, Failed to install 'cordova-plugin-ftp': CordovaError: Uh oh!

### ISSUE THREAD

**Issue by PCX-LK** [deadlyjack/Acode#642]
~~~
yarn run v1.22.19
$ sh utils/scripts/setup.sh
Setting up the project...

added 478 packages, and audited 485 packages in [10](https://github.com/PCX-LK/Acode-Build/actions/runs/4035558008/jobs/6937539058#step:4:11)s

49 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Done in 9.94s.
Using cordova-fetch for cordova-android@^10.1.2
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.foxdebug.acode
	Name: Acode
	Activity: MainActivity
	Android target: android-31
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.2
Removed:  mipmap-ldpi
Removed:  mipmap-hdpi-v26
Removed:  mipmap-ldpi-v26
Removed:  mipmap-mdpi-v26
Removed:  mipmap-xhdpi-v26
Removed:  mipmap-xxhdpi-v26
Removed:  mipmap-xxxhdpi-v26
Removed:  drawable-land-hdpi
Removed:  drawable-land-ldpi
Removed:  drawable-land-mdpi
Removed:  drawable-land-xhdpi
Removed:  drawable-land-xxhdpi
Removed:  drawable-land-xxxhdpi
Removed:  drawable-port-hdpi
Removed:  drawable-port-ldpi
Removed:  drawable-port-mdpi
Removed:  drawable-port-xhdpi
Removed:  drawable-port-xxhdpi
Removed:  drawable-port-xxxhdpi
===============================
== Moved build-extras.gradle ==
===============================
Discovered plugin "cordova-clipboard". Adding it to the project
/home/runner/work/Acode-Build/Acode-Build/Acode/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebView.java updated
/home/runner/work/Acode-Build/Acode-Build/Acode/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebViewEngine.java updated
/home/runner/work/Acode-Build/Acode-Build/Acode/platforms/android/CordovaLib/src/org/apache/cordova/CordovaWebViewEngine.java updated
/home/runner/work/Acode-Build/Acode-Build/Acode/platforms/android/CordovaLib/src/org/apache/cordova/CordovaWebView.java updated
/home/runner/work/Acode-Build/Acode-Build/Acode/platforms/android/CordovaLib/src/org/apache/cordova/CordovaWebViewImpl.java updated
/home/runner/work/Acode-Build/Acode-Build/Acode/platforms/android/.flag_done updated
Installing "cordova-clipboard" for android
Adding cordova-clipboard to package.json
Discovered plugin "cordova-plugin-vibration". Adding it to the project
Installing "cordova-plugin-vibration" for android
Adding cordova-plugin-vibration to package.json
Discovered plugin "cordova-plugin-buildinfo". Adding it to the project
Installing "cordova-plugin-buildinfo" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-buildinfo to package.json
Discovered plugin "cordova-plugin-device". Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Discovered plugin "cordova-plugin-file". Adding it to the project
Installing "cordova-plugin-file" for android
Subproject Path: CordovaLib
Subproject Path: app

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
        
Adding cordova-plugin-file to package.json
Discovered plugin "cordova-plugin-ftp". Adding it to the project
Installing "cordova-plugin-ftp" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-ftp': CordovaError: Uh oh!
"/home/runner/work/Acode-Build/Acode-Build/Acode/plugins/cordova-plugin-ftp/src/android/com/foxdebug/ftp/Ftp.java" not found!
    at copyFile (/home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-android/lib/pluginHandlers.js:208:36)
    at copyNewFile (/home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-android/lib/pluginHandlers.js:233:5)
    at install (/home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-android/lib/pluginHandlers.js:34:17)
    at ActionStack.process (/home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-common/src/PluginManager.js:[11](https://github.com/PCX-LK/Acode-Build/actions/runs/4035558008/jobs/6937539058#step:4:12)2:24)
    at PluginManager.addPlugin (/home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-common/src/PluginManager.js:[14](https://github.com/PCX-LK/Acode-Build/actions/runs/4035558008/jobs/6937539058#step:4:15)2:21)
    at /home/runner/work/Acode-Build/Acode-Build/Acode/node_modules/cordova-android/lib/Api.js:[15](https://github.com/PCX-LK/Acode-Build/actions/runs/4035558008/jobs/6937539058#step:4:16)3:78
Failed to restore plugin "cordova-plugin-ftp". You might need to try adding it again. Error: CordovaError: Uh oh!
"/home/runner/work/Acode-Build/Acode-Build/Acode/plugins/cordova-plugin-ftp/src/android/com/foxdebug/ftp/Ftp.java" not found!
Discovered plugin "cordova-plugin-system". Adding it to the project
Installing "cordova-plugin-system" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-system to package.json
Discovered plugin "cordova-plugin-sftp". Adding it to the project
Installing "cordova-plugin-sftp" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-sftp to package.json
Discovered plugin "cordova-plugin-iap". Adding it to the project
Installing "cordova-plugin-iap" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-iap to package.json
Discovered plugin "cordova-plugin-server". Adding it to the project
Installing "cordova-plugin-server" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-server to package.json

=========================================================
==== Changed provider to com.foxdebug.acode.provider ====
=========================================================

Error: Process completed with exit code 1.
~~~

**Comment by deadlyjack** [comment]
I always build on windows device which doesn't have issue with filename case sensitivity. You need to check file name.

**Comment by PCX-LK** [comment]
> I always build on windows device which doesn't have issue with filename case sensitivity. You need to check file name.

I built with a Github action and didn't change any filenames
Here is the link to Repo：https://github.com/PCX-LK/Acode-Build

**Comment by deadlyjack** [comment]
> 

I mean you need to change the file name for now, I'll fix it next update.

**Comment by PCX-LK** [comment]
> > 
> 
> I mean you need to change the file name for now, I'll fix it next update.

okey
